Repository simplesamlphp/simplesamlphp, pull requests merged in 2018-05, with the labels that each got.

#568 Apache CGI support
  lib/SimpleSAML/Utils/Config.php
  tests/lib/SimpleSAML/Utils/ConfigTest.php
Labels: low, needsinfo

#627 Added metadata configuration options for 'index' and 'isDefault' attributes in AttributeConsumingService element
  lib/SimpleSAML/Metadata/SAMLBuilder.php
  lib/SimpleSAML/Metadata/SAMLParser.php
  modules/saml/docs/sp.md
  modules/saml/www/sp/metadata.php
Labels: enhancement, low

#604 AttributeLimit: allow options to use regex or ignore case.
  modules/core/docs/authproc_attributelimit.md
  modules/core/lib/Auth/Process/AttributeLimit.php
  tests/modules/core/lib/Auth/Process/AttributeLimitTest.php
Labels: enhancement

#441 Make SHA-256 the default signature algorithm.
  config-templates/authsources.php
  docs/simplesamlphp-advancedfeatures.md
  docs/simplesamlphp-changelog.md
  docs/simplesamlphp-reference-idp-hosted.md
  docs/simplesamlphp-reference-idp-remote.md
  docs/simplesamlphp-reference-sp-remote.md
  docs/simplesamlphp-upgrade-notes-1.16.md
  lib/SimpleSAML/Metadata/SAMLParser.php
  lib/SimpleSAML/Metadata/Signer.php
  lib/SimpleSAML/XML/Signer.php
  metadata-templates/saml20-idp-hosted.php
  metadata-templates/saml20-sp-remote.php
  modules/adfs/lib/IdP/ADFS.php
  modules/saml/docs/sp.md
  modules/saml/lib/Message.php
Labels: enhancement, security, started

#564 Improve handling of paths containing Windows-style drive letters
  lib/SimpleSAML/Configuration.php
  lib/SimpleSAML/Utils/System.php
  tests/lib/SimpleSAML/ConfigurationTest.php
Labels: bug

#532 Get consentAdmin to send better state information to processStatePassive
  modules/consentAdmin/www/consentAdmin.php
Labels: enhancement
