Repository simplesamlphp/simplesamlphp, pull requests merged in 2019-08, with the labels that each got.

#1174 Allow themes to inherit module templates
  docs/simplesamlphp-theming.md
  lib/SimpleSAML/XHTML/Template.php
Labels: enhancement

#1183 Twigify exampleauth
  modules/exampleauth/templates/authenticate.twig
  modules/exampleauth/www/authpage.php
Labels: enhancement, maintainability

#1184 Replace mock-test with actual test
  tests/lib/SimpleSAML/Utils/XMLTest.php
Labels: enhancement

#1154 clarify where certs go in IdP quick start docs
  docs/simplesamlphp-idp.md
Labels: docs, good first issue
