Repository simplesamlphp/simplesamlphp, pull requests merged in 2021-03, with the labels that each got.

#1424 Ignore invalid hook names
  lib/SimpleSAML/Module.php
  tests/lib/SimpleSAML/ModuleTest.php
  tests/modules/unittest/README.md
  tests/modules/unittest/hooks/hook_invalid.php.orig
  tests/modules/unittest/hooks/hook_valid.php
  tests/modules/unittest/hooks/invalid_hook_prefix.php
Labels: bug, enhancement

#1440 Conform SAML2INT; check AuthnReqsignature unless specifically disabled
  docs/simplesamlphp-reference-idp-hosted.md
  docs/simplesamlphp-reference-sp-remote.md
  docs/simplesamlphp-upgrade-notes-2.0.md
  modules/saml/lib/Message.php
Labels: SAML2INT compliancy

#1408 Add sanity check to test matching key-pairs
  modules/admin/lib/Controller/Config.php
Labels: enhancement
