Repository simplesamlphp/simplesamlphp, pull requests merged in 2023-07, with the labels that each got.

#1824 full french translation of admin.po (admin module fr locales)
  modules/admin/locales/fr/LC_MESSAGES/admin.po
Labels: translations

#1813 Bugfix: Set destination on signed LogoutResponse for POST and Redirect bindings
  composer.lock
  docs/simplesamlphp-changelog.md
  modules/saml/src/Controller/ServiceProvider.php
Labels: bug, low

#1832 Bugfix: do not expose cron-API if it's not properly configured
  docs/simplesamlphp-changelog.md
  modules/cron/routing/routes/routes.yml
  modules/cron/src/Controller/Cron.php
  tests/modules/cron/src/Controller/CronTest.php
Labels: medium, security

#1828 add support for TLS configuration for Redis Store
  config/config.php.dist
  src/SimpleSAML/Store/RedisStore.php
  tests/src/SimpleSAML/Store/RedisStoreTest.php
Labels: enhancement

#1834 Feature/full tarball
  .github/build/full.json
  .github/build/slim.json
  .github/workflows/build-release.yml
Labels: enhancement
