Repository simplesamlphp/simplesamlphp, pull requests merged in 2023-09, with the labels that each got.

#1857 Replace composer-dependency with phar-file
  .github/workflows/build-release.yml
  .github/workflows/php.yml
  .gitignore
  composer.json
  composer.lock
Labels: enhancement

#1849 Use best available encryption in pwgen.php
  bin/pwgen.php
  composer.json
Labels: enhancement, good first issue

#1792 Restore metadata.sign functionality
  modules/saml/src/IdP/SAML2.php
Labels: bug, medium

#1836 Import the conditional authproc-filters
  docs/simplesamlphp-authproc.md
  src/SimpleSAML/Auth/ProcessingChain.php
  src/SimpleSAML/Auth/ProcessingFilter.php
  tests/src/SimpleSAML/Auth/ProcessingChainTest.php
  tests/src/SimpleSAML/Auth/ProcessingFilterTest.php
Labels: enhancement

#1865 add Accept HTTP headers to MDQ queries
  src/SimpleSAML/Metadata/Sources/MDQ.php
Labels: enhancement, good first issue

#1858 Move the custom Error- and Exception handlers to their own classes
  public/_include.php
  src/SimpleSAML/Error/ErrorHandler.php
  src/SimpleSAML/Error/ExceptionHandler.php
Labels: maintainability
