Repository simplesamlphp/simplesamlphp, pull requests merged in 2024-12, with the labels that each got.

#2345 Use entityID from state to allow overriding the issuer
  modules/saml/src/IdP/SAML2.php
Labels: bug, enhancement

#2346 Feature: Add authproc-filter to be able to manipulate the Assertion's Issuer
  modules/saml/docs/authproc_scopedissuer.md
  modules/saml/src/Auth/Process/ScopedIssuer.php
  tests/modules/saml/src/Auth/Process/ScopedIssuerTest.php
Labels: enhancement

#2260 New 'identifyingAttribute option for SAML Attribute NameID filter
  modules/saml/docs/nameid.md
  modules/saml/src/Auth/Process/AttributeNameID.php
  tests/modules/saml/src/Auth/Process/AttributeNameIDTest.php
Labels: feedback needed
