Repository simplesamlphp/simplesamlphp, pull requests merged in 2024-08, with the labels that each got.

#2208 Add the possibility to continue if no encryption cert is available
  docs/simplesamlphp-reference-idp-hosted.md
  modules/saml/src/IdP/SAML2.php
Labels: enhancement

#2215 Bugfix: Fix regression in language codes
  config/config.php.dist
  docs/simplesamlphp-upgrade-notes-2.3.md
  src/SimpleSAML/Locale/Language.php
  src/SimpleSAML/Locale/Localization.php
Labels: bug

#2222 v23: allow admin password to be stored in config.php without hashing …
  modules/core/src/Auth/Source/AdminPassword.php
Labels: security
